<?php
namespace frontend\models;
use frontend\components\SphinxClient;
use yii\base\Model;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;

class GoodsSearchForm extends Model
{
    public $name;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function search(ActiveQuery $query)
    {
        //加载表单提交的数据
        $this->load(\Yii::$app->request->get());
        if ($this->name) {
            $cl = new SphinxClient();
            $cl->SetServer ( '127.0.0.1', 9312);
            //$cl->SetConnectTimeout ( 10 );
            $cl->SetArrayResult ( true );
// $cl->SetMatchMode ( SPH_MATCH_ANY);
            $cl->SetMatchMode ( SPH_MATCH_ALL);
            $cl->SetLimits(0, 1000);
            $res = $cl->Query($this->name, 'goods');//shopstore_search
            if(isset($res['matches'])){
                $ids = ArrayHelper::getColumn($res['matches'],'id');
                $query->where(['in','id',$ids]);
            }else{
                $query->where(['id'=>0]);
                return;
            }
        }

    }
}